<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_QTY_icon_plus</name>
   <tag></tag>
   <elementGuidId>2a49d499-7ba3-4c5e-94c6-a80072e88c55</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='product-1497']/div/div[2]/form/div/div[2]/div/div/button[2]/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>i.icon_plus</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>dd86933f-e46f-4a67-8a72-2b8041e381b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>icon_plus</value>
      <webElementGuid>c663dde7-78a4-444b-b1d9-3f007e988b3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;product-1497&quot;)/div[@class=&quot;single-product-content&quot;]/div[@class=&quot;summary entry-summary&quot;]/form[@class=&quot;variations_form cart&quot;]/div[@class=&quot;single_variation_wrap&quot;]/div[@class=&quot;woocommerce-variation-add-to-cart variations_button woocommerce-variation-add-to-cart-enabled&quot;]/div[@class=&quot;quantity&quot;]/div[@class=&quot;noo-quantity-attr&quot;]/button[@class=&quot;qty-increase&quot;]/i[@class=&quot;icon_plus&quot;]</value>
      <webElementGuid>629cdc80-d7e4-48b1-9d66-e5b038d2deab</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='product-1497']/div/div[2]/form/div/div[2]/div/div/button[2]/i</value>
      <webElementGuid>ea0ac8d4-fb8f-4f21-a38c-8c5f22e0b4a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[2]/i</value>
      <webElementGuid>3583c199-6eeb-4118-8664-446e082b008c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
