<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__billing_postcode</name>
   <tag></tag>
   <elementGuidId>4a989467-28e0-443d-b496-9bcdf5162267</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='billing_postcode']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#billing_postcode</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b09db665-0226-46c7-b76e-f356dcd7b7e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>75242063-83ee-4cd5-9488-fbdb5f07ca26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-text </value>
      <webElementGuid>1a252552-e15c-475f-ad3c-6f755255577a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>billing_postcode</value>
      <webElementGuid>7840f5ea-6663-4741-9661-9a759bba3b2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>billing_postcode</value>
      <webElementGuid>3eda8799-3cb2-42f8-9896-459d85b1583d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>postal-code</value>
      <webElementGuid>f6bedd29-3b74-46bb-b7d6-e9111022cc19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;billing_postcode&quot;)</value>
      <webElementGuid>cef6eb11-eaee-441c-8912-b0977a6304c7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='billing_postcode']</value>
      <webElementGuid>472c80d1-0c58-4c2a-97a6-ea9e46fde343</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//p[@id='billing_postcode_field']/span/input</value>
      <webElementGuid>f8d88e3f-8e1c-49a3-a58d-ff8a279c6957</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p[9]/span/input</value>
      <webElementGuid>6eed818d-4a96-41bd-b7fd-fa7e93f93b44</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'billing_postcode' and @id = 'billing_postcode']</value>
      <webElementGuid>b299f3df-af13-44c9-bf6b-fe4dac987405</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
