<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Dismiss</name>
   <tag></tag>
   <elementGuidId>df5944a9-4b61-4d7f-bed2-76afaa12e6c5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'Dismiss')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.woocommerce-store-notice__dismiss-link</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>023b3b4e-5017-4b1c-82bd-1fa228273c8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>b2441b77-1d28-4807-b1b9-6595ac9ca935</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>woocommerce-store-notice__dismiss-link</value>
      <webElementGuid>f5d4de6e-61fb-4ffc-a593-a0c91a4cedc8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Dismiss</value>
      <webElementGuid>774d3d00-5e08-4dfc-9c7f-41048f856d41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;yes-js js_active js js no-touch js_active  vc_desktop  vc_transform  vc_transform&quot;]/body[@class=&quot;home page-template page-template-page-full-width page-template-page-full-width-php page page-id-522 wp-custom-logo theme-noo-mebla woocommerce-demo-store woocommerce-js  page-fullwidth full-width-layout wpb-js-composer js-comp-ver-5.7 vc_responsive&quot;]/p[@class=&quot;woocommerce-store-notice demo_store&quot;]/a[@class=&quot;woocommerce-store-notice__dismiss-link&quot;]</value>
      <webElementGuid>2e09d6da-9041-43b2-81bc-a72fba24652d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Dismiss')]</value>
      <webElementGuid>161a4791-0a0b-4cd4-8bbd-e77012b7f22f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='We Work All The Holidays'])[1]/following::a[2]</value>
      <webElementGuid>a6c8f19b-605c-4a70-aa50-bf6e75ee4a5a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sun: Closed'])[1]/following::a[2]</value>
      <webElementGuid>cd84de84-0d56-4ff4-8d80-24ba5bfc270d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Dismiss']/parent::*</value>
      <webElementGuid>92c7d878-aa41-4d7c-b699-f164104d3eba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[10]</value>
      <webElementGuid>af5db47f-2c72-406f-9c29-f42a14b66494</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p/a</value>
      <webElementGuid>71d0cf82-e102-4df9-9b19-dd6c954e4a57</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#' and (text() = 'Dismiss' or . = 'Dismiss')]</value>
      <webElementGuid>727109dc-6029-4ee9-8e61-c0191939fec7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
