<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_SHOP NOW</name>
   <tag></tag>
   <elementGuidId>ad077594-cbeb-4ed0-826c-f6a478b89cf7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='slide-6-layer-9']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#slide-6-layer-9</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>a201a36f-a8b1-458d-bff9-3ee4601b74df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tp-caption   tp-resizeme</value>
      <webElementGuid>66506132-829a-433d-9b9b-434e12f5e65b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>slide-6-layer-9</value>
      <webElementGuid>5f63a14a-b885-4807-b0e7-d3686299d389</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-x</name>
      <type>Main</type>
      <value>center</value>
      <webElementGuid>1e6b0c7f-d2ab-4041-8472-69381733d03f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-y</name>
      <type>Main</type>
      <value>center</value>
      <webElementGuid>ed0718e8-1b6c-441e-8e30-2ef7ef7c46f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-voffset</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>e560c066-7f43-454a-8e94-0654f50e6bf7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-width</name>
      <type>Main</type>
      <value>['auto']</value>
      <webElementGuid>12193493-b559-4477-a051-73eca16a9cdb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-height</name>
      <type>Main</type>
      <value>['auto']</value>
      <webElementGuid>bfff8e32-f3c6-4d19-852e-e584424e13cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>13507da9-e932-41cd-938a-71e6b37ecc21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-responsive_offset</name>
      <type>Main</type>
      <value>on</value>
      <webElementGuid>64575727-572e-478f-8614-ffdb65e9ecf8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-frames</name>
      <type>Main</type>
      <value>[{&quot;delay&quot;:2800,&quot;speed&quot;:1000,&quot;frame&quot;:&quot;0&quot;,&quot;from&quot;:&quot;y:50px;opacity:0;&quot;,&quot;to&quot;:&quot;o:1;&quot;,&quot;ease&quot;:&quot;Power4.easeOut&quot;},{&quot;delay&quot;:&quot;wait&quot;,&quot;speed&quot;:300,&quot;frame&quot;:&quot;999&quot;,&quot;to&quot;:&quot;opacity:0;&quot;,&quot;ease&quot;:&quot;nothing&quot;}]</value>
      <webElementGuid>b2ee0651-b9a7-4a9f-9bae-ba4f5940ecce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-textalign</name>
      <type>Main</type>
      <value>['left','left','left','left']</value>
      <webElementGuid>330ad1d9-3f1b-4588-ab1b-c87d37b83ca3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-paddingtop</name>
      <type>Main</type>
      <value>[0,0,0,0]</value>
      <webElementGuid>db42518c-0147-4db5-ade8-9d3f46ef88a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-paddingright</name>
      <type>Main</type>
      <value>[0,0,0,0]</value>
      <webElementGuid>fdb50a07-e565-4b84-b1fe-dcd3765c661d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-paddingbottom</name>
      <type>Main</type>
      <value>[0,0,0,0]</value>
      <webElementGuid>4dfec5e1-6bf4-4d58-b233-f4c3ecafe28e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-paddingleft</name>
      <type>Main</type>
      <value>[0,0,0,0]</value>
      <webElementGuid>eddec987-4d81-4cbd-9d8a-aa5b02ec4554</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>SHOP NOW > </value>
      <webElementGuid>35f49b5f-d389-4d21-8293-9b8b3cbcc69f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;slide-6-layer-9&quot;)</value>
      <webElementGuid>da80a2df-7210-47ca-8580-ff9b6dc8e4a5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='slide-6-layer-9']</value>
      <webElementGuid>2c887c09-3e2f-4602-81f6-9ade7f619265</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='rev_slider_4_1']/ul/li/div[6]/div/div/div</value>
      <webElementGuid>a5ab94c4-dd9d-4517-9192-f5b0d983b9a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Spring - summer lookbook'])[1]/following::div[8]</value>
      <webElementGuid>501a9a36-c846-48ab-a046-d6fb04a5d7c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='FREE SHIPPING'])[1]/preceding::div[10]</value>
      <webElementGuid>b35860e8-d6b9-4be6-a603-e420082ed683</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Secure payment'])[1]/preceding::div[16]</value>
      <webElementGuid>796c9814-e6e7-4ac7-a348-00ad452cfb3a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='SHOP NOW >']/parent::*</value>
      <webElementGuid>359de241-8762-4ffc-a0e1-c44a78356b17</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/div[6]/div/div/div</value>
      <webElementGuid>131ea577-0cb4-4db1-9958-f6a4bff07e9e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'slide-6-layer-9' and (text() = 'SHOP NOW > ' or . = 'SHOP NOW > ')]</value>
      <webElementGuid>36301d55-5895-4578-b093-a740020fdc78</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
